[project]
name = "conda-docker-demo"
version = "0.0.0"
dependencies = [
  "numpy",
  "torch",
]

[tool.conda-lock]
platforms = [
  "linux-64",
]
channels = [
  "pytorch",
  "conda-forge",
]

[tool.conda-lock.dependencies]
python = "3.11.*"
cpuonly = {}
